-- 고객소리함
DROP TABLE CUSTOM
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CUSTOM;

CREATE TABLE CUSTOM(
SEQ NUMBER(8) PRIMARY KEY,
ID VARCHAR2(50) NOT NULL,
TITLE VARCHAR2(200) NOT NULL,
CONTENT VARCHAR2(4000) NOT NULL,
FILENAMEBF VARCHAR2(50) ,	-- 첨부파일(원본)
FILENAMEAF VARCHAR2(50) ,	-- 첨부파일(바뀐후)
WDATE DATE NOT NULL,
TNAME VARCHAR2(50) NOT NULL,
PROGRESS NUMBER(1) NOT NULL
);

CREATE SEQUENCE SEQ_CUSTOM
START WITH 1
INCREMENT BY 1;

ALTER TABLE CUSTOM
ADD CONSTRAINT FK_CUSTOM_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);