 -- 고객후기
DROP TABLE REVIEW
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_REVIEW;

CREATE TABLE REVIEW(
    SEQ NUMBER(8) PRIMARY KEY,          -- 시퀀스
    ID VARCHAR2(50) NOT NULL,           -- 아이디
    TITLE VARCHAR2(200) NOT NULL,       -- 제목
    CONTENT VARCHAR2(4000) NOT NULL,    -- 내용
    FILENAMEBF VARCHAR2(50),             -- 첨부파일(원본)
    FILENAMEAF VARCHAR2(50),             -- 첨부파일(바뀐후)
    MANAGEMENT VARCHAR2(50) NOT NULL,   -- 관리내용
    READCOUNT NUMBER(8) NOT NULL,       -- 조회수
    WDATE DATE NOT NULL,                -- 작성일
    TNAME VARCHAR2(50) NOT NULL        -- 테이블네임
);

CREATE SEQUENCE SEQ_REVIEW
START WITH 1
INCREMENT BY 1;

ALTER TABLE REVIEW
ADD CONSTRAINT FK_REVIEW_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);



